name = "vpn"
main = "_worker.js"
compatibility_date = "2023-08-23"
[[route]]
pattern = "vpn.bungur.my.id"
custom_domain = true
[[route]]
pattern = "quiz.int.vidio.com.vpn.bungur.my.id"
custom_domain = true

[vars]
UUID = "ba5e7ae5-b3f6-4f8f-8f24-05ba9e3fe81c"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
